### ISSUE TITLE
Update `bootstrap.sh` and `testsuite.sh` to run `test-exec-deserialization.py`

### ISSUE THREAD

**Issue by evverx** [systemd/systemd-centos-ci#14]
`test-exec-deserialization.py` is going to be added by https://github.com/systemd/systemd/pull/5354, so we have to update `bootstrap.sh` and `testsuite.sh` to run it.

**Comment by mrc0mmand** [comment]
Fixed by e4cb16694e96fd8fe5abd4c5f86b92d5f3f1829e (TEST-24-UNIT-TESTS executes all test-* scripts under test directory)

**Comment by evverx** [comment]
I don't think it's fixed because `test-exec-deserialization.py` is a standalone test `-Dinstall-tests` has nothing to do with.

To be honest, I thought `CentOS` was abandoned so I was going to close the issue a long time ago but then apparently totally forgot about it.

**Comment by mrc0mmand** [comment]
My apologies, you're right, that was misunderstatement from my side. I'll look into it tomorrow.

And yes, the CentOS CI was pretty much dead, but we decided to revive it.

**Comment by evverx** [comment]
That's definitely good news. I liked it because it's the only CI that was able to test the transition from initrd. Plus, the kernel was relatively, I'm not sure how to put it, stable, which helped tremendously to catch all new shiny features that didn't exactly work or even compile :-)

I've just found and subscribed to https://github.com/systemd/systemd-centos-ci/issues/18. I hope it'll work out. Thank you for working on this!

**Comment by mrc0mmand** [comment]
Okay, this time it should be indeed resolved - see 195510e8dbc16d752a4247c29fe8a970fb88d8a4. So far the list is rather short, but I'd like to go through all tests under test/ directory and identify those which are not executed by `ninja test` or `run-integration-test.sh`.

**Comment by evverx** [comment]
That should make it work. It'd probably be better to collect the results of the tests and print them at the end instead of failing as soon as the first test returns a non-zero exit code, but it doesn't matter much of course when there's only one test.

**Comment by evverx** [comment]
I've just launched a CentOS VM to see how it works. `bootstrap.sh` failed with
```sh
Looking in links: /tmp/tmp781dns6q
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Successfully installed pip-10.0.1 setuptools-39.0.1
./systemd-centos-ci/slave/bootstrap.sh: line 13: pip3.6: command not found
```
Probably, something like `python3.6 -m pip install meson` should be run instead of `pip3.6 install meson` there.

**Comment by evverx** [comment]
By the way, I think it'd be great to replace "slave" with "agent" everywhere because "agent" seems to be more in line with the official Jenkins terminology.

**Comment by evverx** [comment]
The network issue aside, almost all tests run by `testsuite.sh` seems to be failing because `mkfs -t ext4` isn't working without `e2fsprogs`, which should probably be added to the list at https://github.com/systemd/systemd-centos-ci/commit/195510e8dbc16d752a4247c29fe8a970fb88d8a4#diff-dd048b98ca32d6805823edcdb1c57802R10.

**Comment by evverx** [comment]
And now `copr.fedorainfracloud.org` seems to be down:
```
+ curl https://copr.fedorainfracloud.org/coprs/mrc0mmand/systemd-centos-ci/repo/epel-7/mrc0mmand-systemd-centos-ci-epel-7.repo -o /etc/yum.repos.d/mrc0mmand-systemd-centos-ci-epel-7.repo
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:06 --:--:--     0curl: (7) Failed connect to copr.fedorainfracloud.org:443; Connection timed out
```
and
```
+ curl https://copr.fedorainfracloud.org/coprs/mrc0mmand/systemd-centos-ci/repo/epel-7/mrc0mmand-systemd-centos-ci-epel-7.repo -o /etc/yum.repos.d/mrc0mmand-systemd-centos-ci-epel-7.repo
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    85  100    85    0     0     45      0  0:00:01  0:00:01 --:--:--    45
+ yum -q -y install epel-release yum-utils


File contains no section headers.
file: file:///etc/yum.repos.d/mrc0mmand-systemd-centos-ci-epel-7.repo, line: 1
'{\n'
```
Would it be possible to use something more stable?

**Comment by mrc0mmand** [comment]
First of all, thanks a lot for the testing and debugging.

>Probably, something like python3.6 -m pip install meson should be run instead of pip3.6 install meson there.

This is interesting, as I haven't encountered this issue yet. However, using `python3.6 -m pip` instead of `pip3.6` *should* be more error prone.

>By the way, I think it'd be great to replace "slave" with "agent" everywhere

That definitely makes sense, will do.

>but for some reason after I rebooted the machine network.service failed to bring up eth0

Interesting, another issue I haven't encountered yet. I hope I'll get the creds for the CentOS CI soon, to at least have a yet another different environment to test these things in.

>because mkfs -t ext4 isn't working without e2fsprogs

Good catch, apparently my image has this package already pre-installed.

>Would it be possible to use something more stable?

According to their IRC channel (#fedora-buildsys@Freenode) this should be a *one-time thing*, as they're upgrading their switches.

**Comment by evverx** [comment]
> According to their IRC channel (#fedora-buildsys@Freenode) this should be a one-time thing, as they're upgrading their switches.

If I recall correctly, Fedora CI at least once suddenly [stopped working](https://github.com/systemd/systemd/issues/9456#issuecomment-401790727) due to corp and was down for a few days.

Anyway, I think if I managed to run the tests, `test-exec-deserialization.py` would be the only one that ran and passed without any problems, so it's probably the right time to close the issue.

Thanks again for bringing it back!

**Comment by evverx** [comment]
> was down for a few days

It was more than 10 days actually :-)

**Comment by evverx** [comment]
Regarding the network issue, It appears that the custom kernel isn't quite Virtualbox-friendly. I launched a CentOS VM based on an image released [on October 4th 2018](https://blog.centos.org/2018/10/updated-centos-vagrant-images-available-v1809-01/) with vagrant 2.2.0 using Virtualbox 5.2.20 for Mac OS. After the kernel got upgraded to `4.14.0` it stopped recognizing all the NICs listed at https://www.virtualbox.org/manual/ch06.html#nichardware except for the paravirtualized network adapter. Frankly, I have never heard of virtual environments that can survive kernel upgrades from `3.10` to `4.14`. Virtualbox aside, with such a new kernel, it, strictly speaking, doesn't seem to be CentOS CI anymore. I think it would be better to keep the original kernel provided by the CentOS project.

**Comment by mrc0mmand** [comment]
@evverx Got to the same conclusion during the night. I've already removed the 4.14 kernel from the copr repo, so we're back to 3.10 from the CentOS project. The original reason for 4.14 was my inability to compile upstream systemd on CentOS, but I found out that was caused by a broken OpenStack image, not the kernel itself. Thanks for the confirmation though, will merge my devel branch ASAP.

**Comment by mrc0mmand** [comment]
Okay, I take it back, now I was betrayed by the copr's cache - the build indeed fails:
```
../src/libsystemd/sd-netlink/netlink-types.c:742:10: error: ‘FOU_ATTR_PORT’ undeclared here (not in a function)
         [FOU_ATTR_PORT]              = { .type = NETLINK_TYPE_U16 },
          ^
../src/libsystemd/sd-netlink/netlink-types.c:742:9: error: array index in initializer not of integer type
         [FOU_ATTR_PORT]              = { .type = NETLINK_TYPE_U16 },
         ^
../src/libsystemd/sd-netlink/netlink-types.c:742:9: error: (near initialization for ‘genl_fou_types’)
../src/libsystemd/sd-netlink/netlink-types.c:743:10: error: ‘FOU_ATTR_AF’ undeclared here (not in a function)
         [FOU_ATTR_AF]                = { .type = NETLINK_TYPE_U8 },
          ^
../src/libsystemd/sd-netlink/netlink-types.c:743:9: error: array index in initializer not of integer type
         [FOU_ATTR_AF]                = { .type = NETLINK_TYPE_U8 },
         ^
../src/libsystemd/sd-netlink/netlink-types.c:743:9: error: (near initialization for ‘genl_fou_types’)
../src/libsystemd/sd-netlink/netlink-types.c:744:10: error: ‘FOU_ATTR_IPPROTO’ undeclared here (not in a function)
         [FOU_ATTR_IPPROTO]           = { .type = NETLINK_TYPE_U8 },
          ^
../src/libsystemd/sd-netlink/netlink-types.c:744:9: error: array index in initializer not of integer type
         [FOU_ATTR_IPPROTO]           = { .type = NETLINK_TYPE_U8 },
         ^
../src/libsystemd/sd-netlink/netlink-types.c:744:9: error: (near initialization for ‘genl_fou_types’)
../src/libsystemd/sd-netlink/netlink-types.c:745:10: error: ‘FOU_ATTR_TYPE’ undeclared here (not in a function)
         [FOU_ATTR_TYPE]              = { .type = NETLINK_TYPE_U8 },
          ^
../src/libsystemd/sd-netlink/netlink-types.c:745:9: error: array index in initializer not of integer type
         [FOU_ATTR_TYPE]              = { .type = NETLINK_TYPE_U8 },
         ^
../src/libsystemd/sd-netlink/netlink-types.c:745:9: error: (near initialization for ‘genl_fou_types’)
../src/libsystemd/sd-netlink/netlink-types.c:746:10: error: ‘FOU_ATTR_REMCSUM_NOPARTIAL’ undeclared here (not in a function)
         [FOU_ATTR_REMCSUM_NOPARTIAL] = { .type = NETLINK_TYPE_FLAG },
          ^
../src/libsystemd/sd-netlink/netlink-types.c:746:9: error: array index in initializer not of integer type
         [FOU_ATTR_REMCSUM_NOPARTIAL] = { .type = NETLINK_TYPE_FLAG },
         ^
../src/libsystemd/sd-netlink/netlink-types.c:746:9: error: (near initialization for ‘genl_fou_types’)
[177/1650] Compiling C object 'src/libsystemd/src@libsystemd@@systemd_static@sta/sd-netlink_rtnl-message.c.o'.
ninja: build stopped: subcommand failed.
```

I'll try the [ELrepo](https://elrepo.org/tiki/tiki-index.php) project, which should have more *stable* kernels than my quickly hacked-together copr build.

**Comment by evverx** [comment]
@mrc0mmand I've just opened https://github.com/systemd/systemd/issues/10474. That's exactly what I meant when I was saying about shiny new features that don't exactly work or even compile :-)

**Comment by mrc0mmand** [comment]
@evverx Excellent, thank you very much!

**Comment by mrc0mmand** [comment]
>     * `busybox` was apparently removed so I had to install it manually from https://busybox.net/downloads/binaries/

That explains why Lukas tried to build it in copr when the CentOS CI was working last time. Will fix it.

>     * [`user_namespace.enable=1` should be passed to make `systemd-nspawn -U` work](https://github.com/systemd/systemd/issues/4583).

Will look into it, thanks. I'm still not sure if we should stick with the systemd-nspawn for TEST-??-* test cases or use qemu-kvm instead (or both).
